# Generated by Django 3.0.5 on 2020-05-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwser',
            new_name='Answer',
        ),
    ]
