# Generated by Django 3.0.5 on 2020-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200517_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('has_answered', models.BooleanField(default=False, verbose_name='Has answered')),
                ('questions_answered', models.IntegerField(verbose_name='Questions Answered')),
                ('right_questions', models.IntegerField(verbose_name='Right Questions')),
            ],
        ),
    ]
