# Generated by Django 3.0.5 on 2020-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='questions_answered',
            field=models.IntegerField(default=0, verbose_name='Questions Answered'),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='right_questions',
            field=models.IntegerField(default=0, verbose_name='Right Questions'),
        ),
    ]
